# Домашнее задание к занятию "Парсинг данных"
# Ultra-pro

Возьмите базу квартир moscow.csv.

1. Удалите все строки, которые в столбце "Комнат" имеют значения "Для заметок:".

2. Удалите столбцы "ГРМ", "Источник" и "Примечание".

3. Преобразуйте столбец "Дата" в DataTimeIndex и затем удалите этот столбец.

4. В столбце "От станции" если есть буква "п", то заменить её на слово " минут пешком", если буква "т", то заменить её на " минут на транспорте".

5. Создать новый столбец "Этаж" и заполнить числовыми значениями из столбца "Дом". В столбце "Дом" удалить числовые значения и если есть буква "п", то заменить на "панельный", если буква "к" - "кирпичный", а если буква "м" - "монолитный".

6. Значение столбца "Цена, руб." перевести в млн. руб. и название столбца изменить соответствующе.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%matplotlib inline

import re # регулярные выражения

# Статический вывод графики (графики отображаются в той ячейке, в которой используется plt.show())
import pandas as pd # Импортируем библиотеку обработки и анализа данных pandas
import matplotlib.pyplot as plt # Импортируем модуль pyplot библиотеки matplotlib для построения графиков
import datetime # Импортируем модуль datetime для обработки данных в формете даты
import numpy as np # Импортируем библиотеку numpy
from google.colab import files # Импортируем библиотеку files для работы с файлами

In [ ]:
df = pd.read_csv('/content/drive/My Drive/БД/moscow.csv', sep = ';')

In [ ]:
df.head(20)

,Комнат,Метро / ЖД станции,От станции,Дом,Балкон,Санузел,Площадь,"Цена, руб.",ГРМ,Бонус агенту,Дата,Кол-во дней в экспозиции,Источник,Примечание
0,1,Шелепиха м.,12п,35/37 М,NaN,2,64.1/23/20,19500000.0,NaN,NaN,25.07.2019,1.0,Привлекательные,Собственность оформлена! Ключи на руках! Опера...
1,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Пятницкое шоссе м.,30т,11/14 П,Л,Р,38.4/17/9,4800000.0,NaN,NaN,25.07.2019,2.0,Привлекательные,Зеленоград к.1820 однокомнатная квартира общ.3...
3,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Планерная м.,5т,11/22 П,Б,С,38.2/19.9/9.9,7990000.0,NaN,NaN,25.07.2019,4.0,Привлекательные,"Уютная, светлая квартира, застекленный балкон ..."
5,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,Шаболовская м.,12п,8/12 ?,Б,Р,38/15/7,11200000.0,NaN,NaN,25.07.2019,7.0,Привлекательные,"Предлагаю 1- комн квартиру, в шаговой доступно..."
7,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,Бабушкинская м.,15п,4/14 П,NaN,С,34/17/8,6250000.0,NaN,NaN,25.07.2019,11.0,Привлекательные,Продается хорошая 1 комнатная квартира. 1 взро...
9,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,Шелепиха м.,15п,9/36 К,NaN,NaN,44/14.7/19.2,12700000.0,NaN,NaN,25.07.2019,11.0,Привлекательные,"1-комн. квартира в ЖК ""Сердце столицы"" на 9 эт..."
11,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1,Улица Дмитриевского м.,2п,7/16 П,Л,Р,43/20/8,6500000.0,NaN,NaN,25.07.2019,14.0,Привлекательные,Предлагаю купить Однокомнатную квартиру с удоб...
13,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1,Бульвар Рокоссовского м.,2п,2/5 К,Б,С,31/17/6,6000000.0,NaN,NaN,25.07.2019,15.0,Привлекательные,"Теплая, светлая квартира с высоким потолком в ..."
15,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1,Марьина Роща м.,10п,7/14 П,2Б,NaN,38.9/20.9/8.5,8900000.0,NaN,NaN,25.07.2019,16.0,Привлекательные,"Продается 1-комн. квартира, площадью 38.9 м2 в..."
17,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1,Марьино м.,20п,10/24 М-К,NaN,-,30.9/17.9/10,5999984.0,NaN,NaN,25.07.2019,16.0,Привлекательные,Предлагается уютная квартира в ЖК комфорт клас...
19,Для заметок:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_ = df[::2]
df_ = df_.reset_index(drop = True)
df_ = df_.drop(['ГРМ', 'Источник', 'Примечание'], axis = 1)
df_.index = pd.to_datetime(df_['Дата'])
df_.drop('Дата', axis=1, inplace=True)
tripTime = df_['От станции']
tripTime = tripTime.fillna('Нет данных')
for i in range(tripTime.shape[0]):
  if 'т' in tripTime[i]:
    tripTime[i] = tripTime[i].replace('т', ' минут на транспорте')
  elif 'п' in tripTime[i]:
    tripTime[i] = tripTime[i].replace('п', ' минут пешком')
df_['От станции'] = tripTime
cost = df_['Цена, руб.']
for i in range(cost.shape[0]):
  cost[i] = cost[i] / 1000000
df_['Цена, руб.'] = cost

<ipython-input-15-ef609b22240e>:4: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_.index = pd.to_datetime(df_['Дата'])
<ipython-input-15-ef609b22240e>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cost[i] = cost[i] / 1000000

In [ ]:
df_ = df_.rename(columns = {'Цена, руб.':'Цена, млн. руб.'})

In [ ]:
arr = []
house = df_['Дом']
for i in range(house.shape[0]):
  ind = house[i].find('/')
  el = house[i]
  arr.append(el[:ind])
  if 'П' in house[i]:
    house[i] = 'Панельный'
  elif 'М' in house[i]:
    house[i] = 'Монолитный'
  elif 'К' in house[i]:
    house[i] = 'Кирпичный'
  else:
    house[i] = 'Нет данных'
df_['Этаж'] = arr

<ipython-input-18-c100695a8cde>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house[i] = 'Монолитный'
<ipython-input-18-c100695a8cde>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house[i] = 'Панельный'
<ipython-input-18-c100695a8cde>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house[i] = 'Нет данных'
<ipython-input-18-c100695a8cde>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house[i] = 'Кирпичный'

In [ ]:
df_

,Комнат,Метро / ЖД станции,От станции,Дом,Балкон,Санузел,Площадь,"Цена, млн. руб.",Бонус агенту,Кол-во дней в экспозиции,Этаж
Дата,,,,,,,,,,,
2019-07-25,1,Шелепиха м.,12 минут пешком,Монолитный,NaN,2,64.1/23/20,19.50000,NaN,1.0,35
2019-07-25,1,Пятницкое шоссе м.,30 минут на транспорте,Панельный,Л,Р,38.4/17/9,4.80000,NaN,2.0,11
2019-07-25,1,Планерная м.,5 минут на транспорте,Панельный,Б,С,38.2/19.9/9.9,7.99000,NaN,4.0,11
2019-07-25,1,Шаболовская м.,12 минут пешком,Нет данных,Б,Р,38/15/7,11.20000,NaN,7.0,8
2019-07-25,1,Бабушкинская м.,15 минут пешком,Панельный,NaN,С,34/17/8,6.25000,NaN,11.0,4
...,...,...,...,...,...,...,...,...,...,...,...
2019-12-07,Ст,Некрасовка м.,4 минут пешком,Панельный,NaN,NaN,19.8/?/?,2.85000,NaN,14.0,2
2019-07-23,Ст,Авиамоторная м.,6 минут пешком,Кирпичный,NaN,С,20.4/18/?,3.83999,NaN,14.0,2
2019-12-07,Ст,Коломенская м.,15 минут пешком,Панельный,NaN,NaN,15.4/13.2/?,2.90000,NaN,14.0,1
2019-07-22,Ст,Алтуфьево м.,5 минут на транспорте,Монолитный,NaN,NaN,26/10.9/7,5.20000,NaN,14.0,4
2019-07-25,Ст,Волжская м.,10 минут пешком,Кирпичный,NaN,NaN,17.5/15.2/?,2.79000,NaN,14.0,1